name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            python-version: '3.10'
          - os: ubuntu-latest
            python-version: '3.10'

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt
    
    - name: Build with Nuitka
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          python -m nuitka --mingw64 --windows-disable-console --standalone --output-dir=dist --windows-icon-from-ico=icon.ico wss.py
        else
          python -m nuitka --standalone --output-dir=dist wss.py
        fi
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/wss.dist/wss${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        asset_name: wss-${{ matrix.os == 'windows-latest' && 'windows' || 'linux' }}-${{ github.ref_name }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        asset_content_type: application/octet-stream 
