name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30  # 设置更长的超时时间
    strategy:
      matrix:
        include:
          - os: windows-latest
            python-version: '3.10'
            arch: x64
            output_name: wss-windows-x64.exe
          - os: ubuntu-latest
            python-version: '3.10'
            arch: x64
            output_name: wss-linux-x64
          - os: ubuntu-latest
            python-version: '3.10'
            arch: arm64
            output_name: wss-linux-arm64

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nuitka
        pip install -r requirements.txt
    
    - name: Build with Nuitka (Windows)
      if: matrix.os == 'windows-latest'
      run: python -m nuitka --onefile --standalone --output-dir=dist --output-filename=${{ matrix.output_name }} --assume-yes-for-downloads wss.py
    
    - name: Build with Nuitka (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: python -m nuitka --onefile --standalone --output-dir=dist --output-filename=${{ matrix.output_name }} --assume-yes-for-downloads wss.py
    
    - name: Create Github Release
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./dist/${{ matrix.output_name }}